### ISSUE TITLE
Argo - talend trigger failing

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#206] opened 2016-06-02 09:24 UTC
on AWS 10, the Argo harvester is failing. I can't really understand the reason why
in the file ```/mnt/ebs/log/data-services/ARGO/tmp.M5Yg3G3hIh.20160602-184701.log```
```
/usr/lib/ruby/1.9.1/fileutils.rb:351:in `symlink': File exists - (/mnt/ebs/wip/Argo/dac/aoml/5900927/5900927_Rtraj.nc, /tmp/d20160602-24659-14407wg/IMOS/Argo/dac/aoml/5900927/5900927_Rtraj.nc) (Errno::EEXIST)
        from /usr/lib/ruby/1.9.1/fileutils.rb:351:in `block in ln_s'
        from /usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
        from /usr/lib/ruby/1.9.1/fileutils.rb:349:in `ln_s'
        from /mnt/ebs/talend/bin/talend-trigger:66:in `prepare_file'
        from /mnt/ebs/talend/bin/talend-trigger:163:in `block (3 levels) in handle_files'
        from /mnt/ebs/talend/bin/talend-trigger:162:in `each'
        from /mnt/ebs/talend/bin/talend-trigger:162:in `block (2 levels) in handle_files'
        from /usr/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
        from /mnt/ebs/talend/bin/talend-trigger:161:in `block in handle_files'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `each'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `each_slice'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `each'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `handle_files'
        from /mnt/ebs/talend/bin/talend-trigger:251:in `<main>'
```

@jonescc , do you know what this could be due to ?

**Comment by jonescc** [comment] 2016-06-02 20:50
@lbesnard, the error looks to be happening in the pipeline code preparing the input files for the talend harvester.  I'm not familiar with that code so this will need some investigation.

**Comment by lbesnard** [comment] 2016-06-06 03:25
@pblain

**Comment by pblain** [comment] 2016-06-06 07:19
@lbesnard - it will be part of planning tomorrow

**Comment by bhasin85** [comment] 2016-06-16 06:34
Unable to reproduce the issue on vagrant or production. 

Closing the issue after having discussion with Laurent. @lbesnard

**Comment by lbesnard** [comment] 2016-06-21 02:34
@bhasin85 The issue is unfortunately still there.

see log less /mnt/ebs/log/data-services/ARGO/tmp.jRlip9Pd37.20160621-115618.log
```
ADD '/mnt/ebs/wip/Argo/dac/aoml/5900929/5900929_Rtraj.nc' => 'IMOS/Argo/dac/aoml/5900929/5900929_Rtraj.nc'
/usr/lib/ruby/1.9.1/fileutils.rb:351:in `symlink': File exists - (/mnt/ebs/wip/Argo/dac/aoml/5900927/5900927_Rtraj.nc, /tmp/d20160621-22283-1ghie0u/IMOS/Argo/dac/aoml/5900927/5900927_Rtraj.nc) (Errno::EEXIST)
        from /usr/lib/ruby/1.9.1/fileutils.rb:351:in `block in ln_s'
        from /usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
        from /usr/lib/ruby/1.9.1/fileutils.rb:349:in `ln_s'
        from /mnt/ebs/talend/bin/talend-trigger:66:in `prepare_file'
        from /mnt/ebs/talend/bin/talend-trigger:163:in `block (3 levels) in handle_files'
        from /mnt/ebs/talend/bin/talend-trigger:162:in `each'
        from /mnt/ebs/talend/bin/talend-trigger:162:in `block (2 levels) in handle_files'
        from /usr/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
        from /mnt/ebs/talend/bin/talend-trigger:161:in `block in handle_files'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `each'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `each_slice'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `each'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `handle_files'
        from /mnt/ebs/talend/bin/talend-trigger:251:in `<main>'
```

To replicate the issue :
```
reprocess_files ARGO argo_rsync.20160527-205224.log.20160615-141343_mod.20160621-115618
```


Also I noticed that if I do
```
ll /mnt/ebs/wip/Argo/dac/aoml/5900929/5*
-rw-r--r-- 1 projectofficer projectofficer   29860 May 27 15:38 /mnt/ebs/wip/Argo/dac/aoml/5900929/5900929_meta.nc
-rw-r--r-- 1 root           root           2333516 Jun 11 12:54 /mnt/ebs/wip/Argo/dac/aoml/5900929/5900929_prof.nc
-rw-r--r-- 1 root           root           1374728 Jun 11 11:34 /mnt/ebs/wip/Argo/dac/aoml/5900929/5900929_Rtraj.nc
-rw-r--r-- 1 root           root           1710364 Jun 11 15:35 /mnt/ebs/wip/Argo/dac/aoml/5900929/5900929_tech.nc
```

There is a mix of projectofficer and root user which seems pretty bad to me. @lwgordonimos can you confirm that all PO cron scripts are run as PO user ? ROOT should not be used for data processing.

**Comment by lwgordonimos** [comment] 2016-06-21 04:22
@lbesnard Disregard my previous comments about running as root, they definitely are all set to run as projectofficer (with a couple of exceptions running as normal user accounts, but not root in any case). It looks like the script may have been run manually using sudo, which explains 'root' ownership.

@bhasin85 looks like it may have been you when testing? `sudo ./rsync.sh` Very important not to run these as root, otherwise the file permissions will be all over the place!

**Comment by lwgordonimos** [comment] 2016-06-21 04:32
Further to this, it does look like they are all since the 10th June. I'll look into fixing those permissions now.

**Comment by lbesnard** [comment] 2016-06-27 01:47
@bhasin85 
For the record, I have created a rsync log file with the file being an issue. This log file is located at ```/home/lbesnard/argo_fail_test.log```
its content is ```>f.st...... aoml/5900929/5900929_Rtraj.nc```

I pushed the log file to $INCOMING_DIR/Argo. The pipeline ran fine. No issues whatsoever.

Then I pushed the 'bad' log file again.
```
reprocess_files ARGO argo_rsync.20160527-205224.log.20160615-141343_mod.*
````

And once again, the pipeline failed exactly on the same file for the same reason
```
ADD '/mnt/ebs/wip/Argo/dac/aoml/5900929/5900929_Rtraj.nc' => 'IMOS/Argo/dac/aoml/5900929/5900929_Rtraj.nc'
/usr/lib/ruby/1.9.1/fileutils.rb:351:in `symlink': File exists - (/mnt/ebs/wip/Argo/dac/aoml/5900927/5900927_Rtraj.nc, /tmp/d20160627-30531-zaylz2/IMOS/Argo/dac/aoml/5900927/5900927_Rtraj.nc) (Errno::EEXIST)
        from /usr/lib/ruby/1.9.1/fileutils.rb:351:in `block in ln_s'
        from /usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
        from /usr/lib/ruby/1.9.1/fileutils.rb:349:in `ln_s'
        from /mnt/ebs/talend/bin/talend-trigger:66:in `prepare_file'
        from /mnt/ebs/talend/bin/talend-trigger:163:in `block (3 levels) in handle_files'
        from /mnt/ebs/talend/bin/talend-trigger:162:in `each'
        from /mnt/ebs/talend/bin/talend-trigger:162:in `block (2 levels) in handle_files'
        from /usr/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
        from /mnt/ebs/talend/bin/talend-trigger:161:in `block in handle_files'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `each'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `each_slice'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `each'
        from /mnt/ebs/talend/bin/talend-trigger:157:in `handle_files'
        from /mnt/ebs/talend/bin/talend-trigger:251:in `<main>'
```

A bit hard to understand

**Comment by bhasin85** [comment] 2016-06-30 23:28
Thanks @lbesnard 

This is good as you can replicate the issue. I will be looking into it now. :+1:

**Comment by lbesnard** [comment] 2016-07-15 04:28
thanks @anguss00  for looking at the issue.

However I have a new issue with the harvester. I'm not entirely sure it's completely unrelated, so I put it here. Happy to create a new issue :
___________


The argo harvester complains about a duplicate key in the table platform_metadata. See log
/mnt/ebs/log/data-services/ARGO/tmp.jbwAFOXtUm.20160715-103208.log

The file indeed exists is in file_harvest table
```sql
select * from argo.file_harvest where file_id =1285410
```
But once the harvester has failed, this doesn't return anything (which is good)
```sql
select from argo.platform_metadata where file_id =1285410
```
Since there is no entry already in the table, I tend to think the file is added twice somewhere in the harvester.

But the following two lines don't report any duplicated additions 
```bash
cd $ERROR_DIR/ARGO
get_rsync_additions argo_rsync.20160603-185859.log.20160603-185859.mod.20160715-103208 | sort |uniq -cd
# returns no duplicate input
```
So the list of bulk input files to the harvester seems to be uniq, and this seems to be the case here:
```bash
cat /mnt/ebs/log/data-services/ARGO/tmp.jbwAFOXtUm.20160715-103208.log | grep ADD | sort | uniq -cd
```


There is cleary an issue somewhere. Why this call the same file twice on the same commit (since we don't find anything on platform_metadata table after the run)?

A guru would be really helpful

**Closed** 2016-09-27 01:49 UTC
