### ISSUE TITLE
data.aodn.org.au frontend - can't open folders link

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#239] opened 2016-10-18 23:53 UTC
This is a well known issue, but not written anywhere

The data.aodn.website new frontend brought some nice features (search capability), but also a few bugs such as caching issues, and links which can not be open in a new tab.

The caching issues were solved a few months ago. However, it is still impossible to right click on any s3 folder object, and open the folder in a new tab, or to save the link and paste here in a new tab.

This is quite a basic and also extremely useful feature.

**Comment by lwgordonimos** [comment] 2016-10-19 03:38
@lbesnard the issue is that it's a very Javascript heavy page which is hitting the S3 API and generating the "folders" on this basis.

It's a very basic feature for an actual filesystem, but because this is built on an object store in which folders don't actually exist (only keys which are filtered by their prefix to look like folders), it's not as simple. When it's doing a "folder" request, it really has to hit the API and ask for all object keys with a prefix of "PATH/TO/THE/VIRTUAL/DIR/*" and then make it appear like a folder. There is no way to just do directory listings in the same way as something like Apache on top of a regular file system.

https://github.com/awslabs/aws-js-s3-explorer/blob/master/index.html#L426

You can kind of see the kind of hoops it has to jump through just to pretend that folders exist, by intercepting clicks and constructing URL parameters for a subsequent request to the same index.html in the root of the bucket. It is never actually traversing folders, it is only changing the key filter.

**Comment by smancini** [comment] 2017-01-31 05:54
I have added a "wontfix" label to this issue.
i will close issue because it is not going to be fixed in  the near future. We might reconsider this in a future plan.

**Closed by smancini** 2017-01-31 05:54 UTC
Labels: wontfix
